classDiagram
    class Tag{
        +int id
        +string name
        +Tag()
    }
    class TestCase{
        +int Id
        +string Input
        +string Output
        +bool IsExample
        +TestCase()
    }
    class Problem{
        +int Id
        +string Name
        +Status Status
        +Difficulty Difficulty
        +string Description
        +int TimeLimit
        +int MemoryLimit
        +List<TestCase> TestCases
        +List<Tag> Tags
        +Problem()
    }
    class List~Problem~ {
        # Library Class System.Collections.Generic
    }
    class ProblemList{
        +int Id
        +string Name
        +string Description
        +ProblemList()
    }
    class Assignment{
        +Guid Uid
        +string Name
        +DateTime DueDate
        +string Description
        +User Assigner
        +Status Status
        +Type Type
        +Assignment()
    }
    class Submission{
        +int Id
        +Problem Problem
        +string Code
        +DateTime SubmittedTime
        +Language Language
        +Submission()
    }
    class SubmissionResult{
        +int Id
        +Submission Submission
        +string StandardOutput
        +String StandardError
        +SubmissionResult()
    }
    class AssignmentSubmission{
        +Guid Uid
        +User Submitter
        +Assignment Assignment
        +List<Submission> SubmissionList
        +Status Status
        +AssignmentSubmission()
    }
    class AssignmentSubmissionResult{
        +Guid Uid
        +AssignmentSubmission AssignmentSubmission
        +List<SubmissionResult> SubmissionResultList
        +AssignmentSubmissionResult()
    }
    class Judger{
        -static string _StandardOutput
        -static string _StandardError
        -static string _CompilationOutput
        -static string _CompilationError
        -static string _SourceCodeFilePath
        -static string _SourceCodeFolderPath
        -static string _ExecutableFilePath
        +static void SetSourceCodeFilePath()
        +async static Task<SubmissionResult> RunCode()
        +async static Task<SubmissionResult> JudgeProblem()
        +async static Task<AssignmentSubmission> JudgeAssignment()
        -async static Task<int> Compile()
        -async static Task<int> Execute()
        -static void CompileProcess_Exited()
        -static void CompileProcess_OutputDataReceived()
        -static void CompileProcess_ErrorDataReceived()
        -static void ExecuteProcess_Exited()
        -static void ExecuteProcess_OutputDataReceived()
        -static void ExecuteProcess_ErrorDataReceived()
        -static void Clear()
    }
    class User{
        +Guid Uid
        +string FirstName
        +string LastName
        +string Email
        +Role Role
        +User()
    }
    class Language{
        +string Name
        +bool NeedCompile
        +string CompileCommand
        +string CompileArguments
        +string RunCommand
        +string RunArguments
        +Language()
    }
    List <|-- ProblemList: Inheritance
    ProblemList <|-- Assignment: Inheritance
    Submission --> Judger: Submit to a Judger
    Judger -->  SubmissionResult: Return as the result
    Problem <--> Tag:One to many
    Problem <--> TestCase:One to many
    Problem <--> Submission:One to many
    Language --> Submission
    ProblemList <--> Problem:One to many
    Assignment <--> Problem:One to many
    User <--> Assignment:Create
    User <--> AssignmentSubmission:Create
    AssignmentSubmission --> Judger: Submit to a Judger
    Judger -->  AssignmentSubmissionResult: Return as the result