graph LR
    AlgorithmDynamics[Algorithm Dynamics]
    UI[User Interface]
    DataStructure[Data Structure]
    AlgorithmDynamics --> UI
    UI --> NavigationView
    UI --> HomePage
    UI --> ProblemsPage
    ProblemsPage --> CreateNewProblemPage
    ProblemsPage --> CreateNewProblemListPage
    ProblemsPage --> SearchBox
    ProblemsPage --> ImportExportDialog
    SearchBox --> DatabaseInteration
    UI ---> AssignmentsPage
    AssignmentsPage --> AssignmentsDetailPage
    AssignmentsDetailPage --> TeacherView
    AssignmentsDetailPage --> StudentView
    AssignmentsPage --> AssignmentsListPage
    AssignmentsPage --> CreateNewAssignmentPage
    UI --> PlaygroundPage
    UI --> CodingPage
    CodingPage --> ProblemDisplay
    CodingPage --> CodeEditor
    CodingPage --> IntputOutputErrorBox
    CodingPage --> ProblemNavigator
    UI ---> AccountPage
    AccountPage --> AvatarDisplay
    AccountPage --> LoginButton
    AccountPage --> EditButton
    AccountPage --> StatsDisplay
    UI --> SettingsPage
    SettingsPage --> ThemeSelector
    SettingsPage --> ProgrammingLanguageSelector
    AlgorithmDynamics --> Judger
    Judger --> RunCode
    Judger --> JudgeProblem
    Judger --> JudgeAssignment
    AlgorithmDynamics --> Database
    Database --> AddData
    Database --> SearchData
    Database --> EditData
    Database --> DeleteData
    AlgorithmDynamics --> DataStructure
    DataStructure --> Assignment
    Assignment --> ProblemList
    ProblemList --> Problem
    Problem --> Tag
    Problem --> TestCase
    Assignment --> AssignmentSubmission
    AssignmentSubmission --> AssignmentSubmissionResult
    AssignmentSubmissionResult --> SubmissionResult
    AssignmentSubmission --> Submission
    AlgorithmDynamics --> Networking
    Networking --> GraphAPI
    GraphAPI --> UserLoginAPI
    GraphAPI --> AssignmentAPI
