version: 2
updates:

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/Algorithm Dynamics"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/Algorithm Dynamics.Core/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
