name: Build Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-report:
    name: Build report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build graphs
        run: |
          npm install @mermaid-js/mermaid-cli
          python report/graphs/build_graphs.py

      - name: Build report
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex
          working_directory: report
          extra_system_packages: "py-pygments"
          latexmk_shell_escape: true
          latexmk_use_xelatex: true

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report.pdf
          path: report/report.pdf
          
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    needs: build-report
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Prepare report
        uses: actions/download-artifact@v2
        with:
          name: report.pdf
          path: website/static

      - name: Build website
        run: | 
          cd website
          hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/public
