# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python Application

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 src --count --show-source --statistics
    - name: Test with pytest
      run: |
        pytest --cov=src --cov-config=.coveragerc
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
